### PR TITLE
Support maven build

### PR DESCRIPTION
**Pull request by thuhc-fdssoft**
Add pom.xml that support build by maven

### CODE REVIEW

**Comment by tonowie** [comment]
hi, thank you for contribution. Can you please provide reasoning why we will need 2 builds? All automation is set up to use gradle and I do not see need to maintain maven build alongside of gradle. It is likely that the builds will diverge in time potentially causing issues for someone

**Comment by thuhc-fdssoft** [comment]
Hi,
I'm using maven for all projects, xpx2-java-sdk, applications...
Can you help me how about gradle can deploy package to local repository (~/.m2 or /.gradle) ?
If I use maven build, it will deploy ~/.m2 automatically

-- Thu Cao

**Comment by tonowie** [comment]
simply run following command
./gradlew publishToMavenLocal

also note that library snapshots are published for every commit to master and are publicly available in maven central snapshot repository. so you should not need to build the library at all

**Comment by thuhc-fdssoft** [comment]
Yes, I need java-xpx-chain-sdk on maven central ? is it there ?

-- Thu Cao

**Comment by thuhc-fdssoft** [comment]
./gradlew publishToMavenLocal
> Task :signMavenJavaPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signMavenJavaPublication'.
> Cannot perform signing task ':signMavenJavaPublication' because it has no configured signatory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
7 actionable tasks: 6 executed, 1 up-to-date

**Comment by tonowie** [comment]
closing this as we will not be managing 2 builds

**Pull request closed without merging**
